### ISSUE TITLE
read, clean, and validate linelist

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials-early#21]
created branch to assess any deployment issues https://github.com/epiverse-trace/tutorials-early/tree/fix-read-describe-cases/

**Comment by Degoot-AM** [comment]
Thanks @avallecam. Should I delete these branches: `early-task-read`, `early-task-clean`, and `early-task-describe`. Because, I see you had put all their files into this new branch `fix-read-descrbie-cases`, and it nice to cut the clutter of too many branches.

**Comment by avallecam** [comment]
> Thanks @avallecam. Should I delete these branches: `early-task-read`, `early-task-clean`, and `early-task-describe`. Because, I see you had put all their files into this new branch `fix-read-descrbie-cases`, and it nice to cut the clutter of too many branches.

Could we use the `early-task-clean` as a placeholder for episodes on the "data cleaning" task? I think that is still not covered by any of us yet.

After merging #10 and #15 those branches are deleted automatically.
